'use client';

import { useActionState } from 'react';
import {
  finalizePoomsaeAction,
  generateDrawAction,
  issueCertificatesAction,
  setDrawStatus,
  type AdminState,
} from '@/actions/admin';
import { SubmitButton } from '@/components/SubmitButton';
import { FormMessage } from '@/components/FormMessage';
import { Card, Field } from '@/components/ui';
import { EventIdField } from '@/components/EventIdField';

export function CategoryDrawPanel({
  categoryId,
  event,
  drawStatus,
  finalized,
  approvedEntries,
}: {
  categoryId: string;
  event: string;
  drawStatus: string;
  finalized: boolean;
  approvedEntries: number;
}) {
  const [genState, genAction] = useActionState<AdminState, FormData>(generateDrawAction, null);
  const [statusState, statusAction] = useActionState<AdminState, FormData>(setDrawStatus, null);
  const [finalState, finalAction] = useActionState<AdminState, FormData>(finalizePoomsaeAction, null);
  const [certState, certAction] = useActionState<AdminState, FormData>(issueCertificatesAction, null);

  return (
    <div className="space-y-6">
      <Card title={event === 'KYORUGI' ? 'Generate bracket' : 'Generate performance order'}>
        <form action={genAction} className="space-y-4">
          <EventIdField />
          <FormMessage state={genState} />
          <input type="hidden" name="categoryId" value={categoryId} />

          {event === 'KYORUGI' && (
            <Field label="Seeding" name="strategy">
              <select id="strategy" name="strategy" className="select" defaultValue="BELT">
                <option value="BELT">By belt grade</option>
                <option value="RANDOM">Fully random</option>
              </select>
            </Field>
          )}

          <p className="text-sm text-ink-soft">
            {approvedEntries === 0
              ? 'No approved entries — nothing to draw yet.'
              : `${approvedEntries} approved entr${approvedEntries === 1 ? 'y' : 'ies'} will be drawn.`}
          </p>

          <SubmitButton
            className="btn-dark w-full"
            pendingLabel="Generating…"
            confirm={
              drawStatus === 'PUBLISHED'
                ? 'This draw is already published. Regenerating replaces the bracket and discards recorded results. Continue?'
                : undefined
            }
          >
            {drawStatus === 'DRAFT' ? 'Generate' : 'Regenerate'}
          </SubmitButton>
        </form>
      </Card>

      <Card title="Draw status">
        <form action={statusAction} className="space-y-4">
          <EventIdField />
          <FormMessage state={statusState} />
          <input type="hidden" name="categoryId" value={categoryId} />

          <Field
            label="Visibility"
            name="status"
            hint="Published draws appear on the school dashboards and the public page. Locked draws cannot be regenerated by mistake."
          >
            <select id="status" name="status" className="select" defaultValue={drawStatus}>
              <option value="DRAFT">Draft — internal only</option>
              <option value="GENERATED">Generated — internal only</option>
              <option value="PUBLISHED">Published — visible to everyone</option>
              <option value="LOCKED">Locked — final</option>
            </select>
          </Field>

          <SubmitButton className="btn-ghost w-full" pendingLabel="Saving…">
            Update status
          </SubmitButton>
        </form>
      </Card>

      {event === 'POOMSAE' && !finalized && (
        <Card title="Finalise Poomsae" subtitle="Computes each score, ranks the field and awards medals.">
          <form action={finalAction} className="space-y-3">
            <EventIdField />
            <FormMessage state={finalState} />
            <input type="hidden" name="categoryId" value={categoryId} />
            <SubmitButton
              className="btn-primary w-full"
              pendingLabel="Finalising…"
              confirm="Finalise this category and award medals? Every entry must already have judge scores."
            >
              Finalise &amp; award medals
            </SubmitButton>
          </form>
        </Card>
      )}

      {finalized && (
        <Card title="Certificates" subtitle="Participation for every entrant, merit for medallists.">
          <form action={certAction} className="space-y-3">
            <EventIdField />
            <FormMessage state={certState} />
            <input type="hidden" name="categoryId" value={categoryId} />
            <SubmitButton className="btn-primary w-full" pendingLabel="Issuing…">
              Issue certificates
            </SubmitButton>
          </form>
        </Card>
      )}
    </div>
  );
}
